name: Build, Test and Push

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build_and_test:
    name: Build and test
    uses: ./.github/workflows/build_and_test.yml

  docker_push:
    name: Build & push Docker image
    needs: build_and_test
    uses: ./.github/workflows/docker_push.yml
    with:
      image-tags: latest
    permissions:
      packages: write
      contents: read

  release_crate:
    name: Release new crate
    needs: build_and_test
    uses: ./.github/workflows/release_cargo.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
  

    