name: Build, Test and Push

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build_and_test:
    name: Build and test
    uses: ./.github/workflows/build_and_test.yml

  docker_push:
    name: Build & push Docker image
    needs: build_and_test
    uses: ./.github/workflows/docker_push.yml
    with:
      image-tags: latest
    permissions:
      packages: write
      contents: read

    